### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by GaryREM** [therippa/tesla-bitbar#10]
Getting the following:
Traceback (most recent call last):
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 400, in <module>
    main()
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 281, in main
    vehicles = c.vehicles()
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 94, in vehicles
    return [Vehicle(v, self) for v in self.get('vehicles')['response']]
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 116, in get
    return self.post(command, None)
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 125, in post
    return self.__open("%s%s" % (self.api, command), headers=self.head, data=data)
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 162, in __open
    if check_token_age():
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 248, in check_token_age
    if datetime.datetime.strptime(token_date, '%Y-%m-%d') <= datetime.datetime.now() - datetime.timedelta(days=45):
TypeError: must be string, not None

Any advice?

**Comment by dsbilling** [comment]
Fixed. Waiting for @therippa to accept the changes.

**Comment by therippa** [comment]
merged

**Comment by GaryREM** [comment]
Thanks for fixing!
