### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by markmoroni** [therippa/tesla-bitbar#14]
I've been using this tesla-bitbar plugin for a couple years now to keep tabs on my car while at work.  Recently, however, when attempting to log in, I have been receiving an error via the terminal (please see output below).  Not too certain whether Tesla changed their login mechanism, or whether something within macOS has changed (currently using macOS 11.2.1)

$ ./tesla.30m.py login    

tesla.com username (will not be saved): <hidden>
tesla.com password (will not be saved): 
Checking...Click to login | refresh=true terminal=true bash="/Users/user/Documents/Bitbar/tesla.30m.py" param1=login
Traceback (most recent call last):
  File "/Users/user/Documents/Bitbar/tesla.30m.py", line 426, in <module>
    main()
  File "/Users/user/Documents/Bitbar/tesla.30m.py", line 283, in main
    prompt_login()
  File "/Users/user/Documents/Bitbar/tesla.30m.py", line 230, in prompt_login
    access_token = c.get_token()
  File "/Users/user/Documents/Bitbar/tesla.30m.py", line 106, in get_token
    if 'access_token' in auth and auth['access_token']:
TypeError: argument of type 'NoneType' is not iterable
$

Any help would be appreciated!

**Comment by dsbilling** [comment]
This is probably because Tesla now uses 2FA, so this needs a rewrite.

**Comment by therippa** [comment]
I don't own a Tesla anymore, so there is no way for me to fix this.

**Comment by dsbilling** [comment]
> I don't own a Tesla anymore, so there is no way for me to fix this.

Same 😅
