### ISSUE TITLE
Login function does not work

### ISSUE THREAD

**Issue by GaryREM** [therippa/tesla-bitbar#6]
If I directly supply an access token, things work.

However, there is a login function which is supposed to be there if things fail. However, the function does not work, i.e. a login request does not ever appear.

--Error contacting Tesla's servers
Traceback (most recent call last):
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 391, in <module>
    main()
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 272, in main
    vehicles = c.vehicles()
  File "/Users/grmensz/Documents/BitBarPlugins/tesla.30m.py", line 95, in vehicles
    return [Vehicle(v, self) for v in self.get('vehicles')['response']]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by GaryREM** [comment]
OK, followed your new instruction about resetting keyring and got things to work.

Awkward...
